### ISSUE TITLE
Unable to load .sql files from a relative path?

### ISSUE THREAD

**Issue by Schachte** [gchaincl/dotsql#19]
I'm trying to load in a sql file from my package relative to the current package path:

```
	tables, err := dotsql.LoadFromFile("../sql/tables.sql")

	if err != nil {
		fmt.Println(err)
		fmt.Println("failed at tables")
		os.Exit(1)
	}
```

This is erroring out with file not found, but it's the right path. Any tips?

Edit: Is it always relative to where the main is? Wondering if I just specify relative to main when I build the bundle the files into the binary using gotic after the fact so I can still have a single static binary.

**Comment by gchaincl** [comment]
It's relative from where the executable file is, just to make sure, try printing the result of [os.Getwd] (https://golang.org/pkg/os/#Getwd) and that should be the path you are.
And yes, embedding the sql file is probably the way to go

**Comment by Schachte** [comment]
Great, thanks
